windows_service_accounts:
  prod:
    username: "win_prod_user"
    password: "win_prod_pass"
  nonprod:
    username: "win_nonprod_user"
    password: "win_nonprod_pass"
linux_service_accounts:
  prod:
    username: "linux_prod_user"
    password: "linux_prod_pass"
  nonprod:
    username: "linux_nonprod_user"
    password: "linux_nonprod_pass"
