$ANSIBLE_VAULT;1.1;AES256
38303737323239313532353131353436646461663464643161663734393139393261356133383533
3339346430643862633933393238613634333766643665620a353864383861313962653638383838
61636136353839303166326139366130323835376661383739613466633434346236386664613163
6132303466336463310a343436623363623565383335393764303335323831613438613639616330
34383837396631343534346333376639326665643233653337633365623261616365333963383732
39313931303663653861643430316461303763633836336231633365633732346364306265663663
38393264613132353630383462336235383035383961366163636538333732623232616339306232
31633333386132363239396237663766616530303462613361346139313831643632356630643965
62656534333535626237383739643163616339616433636133323661333637346430376566396537
63383033363062306266303632366364313761353664623630643362303261343332336330626530
30653361393561323535646161646339383832643231656635396230323733666261316139623762
34653264343930373264653438376333313163646536646131623639333333333630393634346337
6338
