ansible_windows_accounts:
  prod:
    ansible_user: "win_prod_user"
    ansible_password: "win_prod_pass"
  nonprod:
    ansible_user: "win_nonprod_user"
    ansible_password: "win_nonprod_pass"
ansible_linux_accounts:
  prod:
    ansible_user: "linux_prod_user"
    ansible_ssh_pass: "linux_prod_pass"
  nonprod:
    ansible_user: "linux_nonprod_user"
    ansible_ssh_pass: "linux_nonprod_pass"
