- name: Include Linux tasks
  import_tasks: linux.yml
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Include Windows tasks
  import_tasks: windows.yml
  when: ansible_os_family == 'Windows'
